%% demo one
disp('demo one')
graph_mat = [1 2; ...
             2 3; ...
             3 4; ...
             4 1; ...
             2 4];
weights = [3 4 3 5];
[vertex_set_indices, prices] = vertex_cover_approx(graph_mat, weights);
disp(vertex_set_indices)
disp(prices)

%% demo two
disp('demo two')
graph_mat = [1 2; ...
             1 3; ...
             1 6; ...
             2 4; ...
             2 5; ...
             3 4; ...
             3 5; ...
             4 6; ...
             5 6];
weights = 11 : -2 : 1;
[vertex_set_indices, prices] = vertex_cover_approx(graph_mat, weights);
disp(vertex_set_indices)
disp(prices)

%% demo three (optional)
% create a large-scale graph instance to show the performance of the pricing method
disp('demo three')
graph_mat = [1 2; ...
             1 3; ...
             1 4; ...
             2 3; ...
             3 4];
weights = [4,3,5,3];
[vertex_set_indices, prices] = vertex_cover_approx(graph_mat, weights);
disp(vertex_set_indices)
disp(prices)


